### ISSUE TITLE
Regularization images for SDXL

### ISSUE THREAD

**Issue by robertJene** [tobecwb/stable-diffusion-regularization-images#4]
can you please create regularization images in 1024x1024 resolution for SDXL

**Comment by tobecwb** [comment]
I am currently generating new images in better quality for SD 1.5, 2.1 and SDXL.
All images will have post processing to ensure quality, so it will take a few days/weeks, but images for SDXL are on the list

**Comment by robertJene** [comment]
Let me know via a comment on one of my videos or an Instagram DM when you are done, thanks.
my IG is @PerRevolutions

**Comment by tobecwb** [comment]
I was looking at your other videos, especially the SDXL LoRA training (https://www.youtube.com/watch?v=tccLepvMKO0), and I thought you could help me.
I currently have a 3060 and it's difficult to do some tests with it, due to its speed (normally I rent some servers with the 3090, 4090, A4000, A5000, etc., but the cost is a bit high to just do tests).

I still haven't been able to conclude whether it's better for regularization images to be a bunch of random things that resemble "woman" (example: https://github.com/tobecwb/stable-diffusion-Regularization-Images/blob/main/sd2.1/woman/1117-photo%20of%20a%20woman.jpg), or use a more realistic style (like photos).

I generated around 1300 images, using SDXL, and mainly, a lot of negative prompts, and I couldn't come to a conclusion whether this helps or make it worse. All my tests so far have shown that if I don't use these regularization images is better than using them. I don't know if this is because of SDXL (I don't have much practice), if it's because of the negative prompts I used when generating the regularization images, or if I'm doing something wrong.

If you can help me come to a conclusion, I can upload the images in a separate branch, and you could do some testing for me.
