### ISSUE TITLE
Downloading issues 

### ISSUE THREAD

**Issue by Pmazil** [tobecwb/stable-diffusion-regularization-images#6]
Downloading issues even with Github Desktop

**Comment by tobecwb** [comment]
This repository contains more than 10GB of data. You will hardly be able to download using any other way than `git clone`.
I had to make several commits to upload all the files, due to some git limitations.
I believe these limitations apply to downloading as well.

I tested on 3 different ISPs, and although it took a while, `git clone` worked every time.

**Comment by tobecwb** [comment]
I created some releases, separated by class and version of Stable Diffusion.
Try downloading through the files available in release (https://github.com/tobecwb/stable-diffusion-regularization-images/releases)

**Comment by robertJene** [comment]
I can verify that git clone works good.
